services:
  grafana:
    hostname: grafana{{.Task.Slot}}
    image: $GRAFANA_IMAGE
    ports:
      - mode: host
        published: $GRAFANA_PORT
        target: $GRAFANA_PORT
        protocol: tcp
    secrets:
      - source: grafana_crt
        target: /etc/grafana/tls/grafana.crt
      - source: grafana_key
        target: /etc/grafana/tls/grafana.key
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_ADMIN_PASS

      GF_SERVER_PROTOCOL: https
      GF_SERVER_CERT_FILE: /etc/grafana/tls/grafana.crt
      GF_SERVER_CERT_KEY: /etc/grafana/tls/grafana.key
    deploy:
      mode: replicated
      replicas: $GRAFANA_REPLICAS
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.${STACK}_grafana == 1

secrets:
  grafana_crt:
    file: ${SECRETS}/grafana.crt
  grafana_key:
    file: ${SECRETS}/grafana.key

volumes:
  grafana-data:
