#!/usr/bin/env bash

# -----------------------------------------------------
# Helper functions
# -----------------------------------------------------

function check_stack_context {
  if [[ -z "${GRAFANA_ADMIN_PASS:-}" ]]; then
    log_error "GRAFANA_ADMIN_PASS missing from 'secrets.env'."
    exit 1
  fi
}

function build_secrets {
  if [[ ! -f "$SECRETS/ca.crt" || ! -f "$SECRETS/ca.key" ]]; then
    make-ca monitoring -o "$SECRETS"
    make-truststore monitoring "$SECRETS/ca.crt" -o "$SECRETS"
  fi
  
  if [[ ! -f "$SECRETS/grafana.crt" || ! -f "$SECRETS/grafana.key" ]]; then
    make-cert grafana "$GRAFANA_NODES $GRAFANA_FQDN_NODES" -o "$SECRETS" --ca-crt "$SECRETS/ca.crt" --ca-key "$SECRETS/ca.key"
  fi

  if [[ ! -f "$SECRETS/victorialogs.crt" || ! -f "$SECRETS/victorialogs.key" ]]; then
    make-cert victorialogs "$VICTORIALOGS_NODES $VICTORIALOGS_FQDN_NODES" -o "$SECRETS" --ca-crt "$SECRETS/ca.crt" --ca-key "$SECRETS/ca.key"
  fi
}

function grafana_health {
  local resp http_code start now elapsed

  log_info "Waiting for Grafana to become healthy…"

  start=$(date +%s)
  while true; do
    resp=$(curl -s -w "\n%{http_code}" "https://grafana.$DOMAIN/api/health")
    http_code="${resp: -3}"

    if [[ "$http_code" == "200" ]]; then
      log_info "Grafana ready."
      break
    fi

    now=$(date +%s)
    elapsed=$(( now - start ))

    if (( elapsed > 300 )); then
      log_error "Grafana did not become ready within 5 minutes."
      exit 1
    fi

    sleep 5
  done
}

function grafana_install_plugins {
  local grafana_node container_id
  
  grafana_node=$(first "$GRAFANA_FQDN_NODES")
  container_id=$(docker -H "ssh://$grafana_node" ps --filter "name=${STACK}_grafana" --filter status=running -q)

  docker -H "ssh://$grafana_node" exec "$container_id" grafana cli plugins install victoriametrics-logs-datasource

  log_info "Plugins installed or updated. A re-deploy may be necessary."
}

# -----------------------------------------------------
# Stack functions
# -----------------------------------------------------

function stack_check_env {
  if [ ! -d "$SECRETS" ]; then
    echo "Secrets directory is missing from '$ENVIRONMENT_BASE'."
    exit 1
  fi
}

function stack_discover {
  export GRAFANA_REPLICAS=$(count "$GRAFANA_NODES")
  export VICTORIALOGS_REPLICAS=$(count "$VICTORIALOGS_NODES")
}

function stack_env {
  echo
  echo "GRAFANA IMAGE      = $GRAFANA_IMAGE"
  echo "GRAFANA NODES      = ($GRAFANA_REPLICAS)"
  list "$GRAFANA_NODES"
  echo
  echo "VICTORIALOGS IMAGE = $VICTORIALOGS_IMAGE"
  echo "VICTORIALOGS NODES = ($VICTORIALOGS_REPLICAS)"
  list "$VICTORIALOGS_NODES"
  echo
  echo "UDP/TCP PORT       = $VICTORIALOGS_UDP_PORT/$VICTORIALOGS_TCP_PORT"
  echo
}

function stack_deploy {
  check_stack_context
  build_secrets
  docker stack deploy --detach=true -c victorialogs.yml -c grafana.yml "$STACK"
  grafana_health
  grafana_install_plugins
}
