services:
  victorialogs:
    hostname: victorialogs{{.Task.Slot}}
    image: $VICTORIALOGS_IMAGE
    ports:
      - mode: host
        published: $VICTORIALOGS_UDP_PORT
        target: $VICTORIALOGS_UDP_PORT
        protocol: udp
      - mode: host
        published: $VICTORIALOGS_TCP_PORT
        target: $VICTORIALOGS_TCP_PORT
        protocol: tcp
      - mode: host
        published: $VICTORIALOGS_HTTP_PORT
        target: $VICTORIALOGS_HTTP_PORT
        protocol: tcp
    secrets:
      - source: victorialogs_crt
        target: /etc/victorialogs/tls/victorialogs.crt
      - source: victorialogs_key
        target: /etc/victorialogs/tls/victorialogs.key
    volumes:
      - victorialogs-data:/var/lib/victoria-logs
    command:
      - "--storageDataPath=/var/lib/victoria-logs"
      - "--syslog.listenAddr.udp=:$VICTORIALOGS_UDP_PORT"
      - "--syslog.listenAddr.tcp=:$VICTORIALOGS_TCP_PORT"
      - "--tls"
      - "--tlsCertFile=/etc/victorialogs/tls/victorialogs.crt"
      - "--tlsKeyFile=/etc/victorialogs/tls/victorialogs.key"
      - "--retentionPeriod=30d"
    deploy:
      mode: replicated
      replicas: $VICTORIALOGS_REPLICAS
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.${STACK}_victorialogs == 1

secrets:
  victorialogs_crt:
    file: ${SECRETS}/victorialogs.crt
  victorialogs_key:
    file: ${SECRETS}/victorialogs.key

volumes:
  victorialogs-data:
