{
 "title": "Nginx Dashboard",
 "description": "Nginx insights dashboard based on https://grafana.com/grafana/dashboards/24774-nginx-with-vlogs/",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "victoriametrics-logs-datasource"
   }
  ]
 },
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "total_req",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | _time:24h | stats count() as total_req"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | stats by(status) count() as requests"
    }
   ]
  },
  {
   "title": "NGINX logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | stats sum_len(_msg) messages_len"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | stats by (host) sum(body_bytes_sent) as TotalBytes"
    }
   ]
  },
  {
   "title": "% of 4xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "$A / $B * 100", "type": "math" }
   ]
  },
  {
   "title": "Realtime visitors ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | _time:5m | count_uniq(remote_addr)"
    }
   ]
  },
  {
   "title": "NGINX log lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | stats count(_msg) msg_lines"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "$A / $B * 100", "type": "math" }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "description": "最近请求",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "desc",
     "expr": "internal_tag: \"nginx\" | extract '<method> <uri> <protocol>' from _msg | format \"<method> <uri> with HTTP status: <status> From <remote_addr>\" ",
     "maxLines": 100
    }
   ]
  },
  { "title": "Request statistics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | stats quantile(0.95, request_time)"
    },
    {
     "expr": "internal_tag: \"nginx\" | stats max(request_time)"
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | stats by (status) count()"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" status:200 | stats sum(body_bytes_sent)"
    }
   ]
  },
  { "title": "Acquisition and Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Top 10 User Agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | top 11 by (user_agent)",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Top 10 HTTP Referers",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | top 11 by (referer)"
    }
   ]
  },
  {
   "title": "Top 10 visitor IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | top 11 by (remote_addr) hits as Requests"
    }
   ]
  },
  {
   "title": "Top 10 Requested Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 39 },
   "targets": [
    {
     "expr": "internal_tag: \"nginx\" | top 11 by (server_name) hits as Total"
    }
   ]
  }
 ]
}